---
Name: simpledatefield
After: '#adminroutes'
---
SilverStripe\Control\Director:
  rules:
    'formfields-simpledatefield//$Action/$Value': 'Sunnysideup\DatefieldSimplified\SimpleDateFieldController'
